@startuml
'https://plantuml.com/activity-diagram-beta

start
:业务端请求;
:actoken;
:获取token;
if (分页) then (true)
  if (分页是否在500条第一页) then (no)
    :查询总条数;
    if (总条数大于500) then (true)
      stop
    endif

    if (isPost?) then (yes)
      :Page.onPost();
    else (no)
      :Page.onGet();
    endif
    :Page.onRender();
  endif
else (false)
endif

if (do redirect?) then (yes)
  :redirect process;
else
  if (do forward?) then (yes)
    :Forward request;
  else (no)
    :Render page template;
  endif
endif

stop

@enduml
